### ISSUE TITLE
Git master fails to build with Visual Studio 2017

### ISSUE THREAD

**Issue by cgohlke** [schrodinger/pymol-open-source#126]
fa732f6 fails to compile with MSVC 14.16.27023 on Windows:
```
Block.cpp
layer1\CGO.h(662): error C2440: 'static_cast': cannot convert from 'const float' to 'cCylCap'
layer1\CGO.h(662): note: Conversions between enumeration and floating point values are no longer allowed
layer1\CGO.h(663): error C2440: 'static_cast': cannot convert from 'const float' to 'cCylCap'
layer1\CGO.h(663): note: Conversions between enumeration and floating point values are no longer allowed
layer1\CGO.h(682): error C2440: 'static_cast': cannot convert from 'const float' to 'cCylCap'
layer1\CGO.h(682): note: Conversions between enumeration and floating point values are no longer allowed
layer1\CGO.h(683): error C2440: 'static_cast': cannot convert from 'const float' to 'cCylCap'
layer1\CGO.h(683): note: Conversions between enumeration and floating point values are no longer allowed
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```
